In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# Create a numpy array filled with all ones by defining its shape

In [3]:
import numpy as np
shape=(3,3)
print(np.ones(shape))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# How do you remove rows from a Numpy array that contains non-numeric values?

In [5]:
arr=np.array([
    [1,2,3],
    [2,'a',3],
    ['a','b','c']
])
print(arr)

[['1' '2' '3']
 ['2' 'a' '3']
 ['a' 'b' 'c']]
